import { Radio, Square } from 'lucide-react'
import { useState, type FormEvent, type ReactNode } from 'react'
import { Badge } from '../../components/ui/badge'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import type { ReceiverSnapshot, StartReceiverRequest } from '../../platform/BeamDropApi'

export function ReceiverPanel({ receiver, onStart, onStop, busy }: { receiver: ReceiverSnapshot; onStart: (request: StartReceiverRequest) => Promise<void>; onStop: () => Promise<void>; busy: boolean }) {
  const [host, setHost] = useState(receiver.host ?? '0.0.0.0'); const [port, setPort] = useState(String(receiver.port ?? 9090)); const [saveDir, setSaveDir] = useState(receiver.saveDir ?? 'received'); const [error, setError] = useState<string | null>(null)
  const running = receiver.state === 'running' || receiver.state === 'starting' || receiver.state === 'stopping'
  async function start(event: FormEvent) { event.preventDefault(); const parsedPort = Number(port); if (!host.trim() || !saveDir.trim() || !Number.isInteger(parsedPort) || parsedPort < 1 || parsedPort > 65535) { setError('请填写监听地址、有效端口和保存目录。'); return }; setError(null); await onStart({ host: host.trim(), port: parsedPort, saveDir: saveDir.trim() }) }
  return <section className="monument-panel p-5"><div className="mb-5 flex items-start justify-between gap-3"><h2 className="monument-section-title">接收服务</h2><Badge className={running ? 'border-emerald-400/30 bg-emerald-500/10 text-emerald-300' : ''}>{receiver.state}</Badge></div><form className="grid gap-4" onSubmit={start}><div className="grid gap-4 sm:grid-cols-[1fr_9rem]"><Field label="监听地址"><Input value={host} disabled={running} onChange={(event) => setHost(event.target.value)} /></Field><Field label="端口"><Input value={port} disabled={running} onChange={(event) => setPort(event.target.value)} /></Field></div><Field label="保存目录"><Input value={saveDir} disabled={running} onChange={(event) => setSaveDir(event.target.value)} /></Field>{(error ?? receiver.lastError?.message) && <p className="text-sm text-rose-300">{error ?? receiver.lastError?.message}</p>}{running ? <Button className="monument-button" type="button" variant="outline" disabled={busy || receiver.state === 'stopping'} onClick={() => void onStop()}><Square size={15} />{receiver.state === 'stopping' ? '正在停止' : '停止接收'}</Button> : <Button className="monument-button" type="submit" disabled={busy}><Radio size={16} />{busy ? '正在启动' : '启动接收'}</Button>}</form></section>
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="monument-field grid gap-1.5 text-sm font-medium">{label}{children}</label> }